version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: sre_postgres
    environment:
      POSTGRES_USER: sre_user
      POSTGRES_PASSWORD: sre_password
      POSTGRES_DB: sre_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
